ports:
  - port: 8000
    visibility: public
    onOpen: open-preview

tasks:
  - before: |
      echo 'Beginning before stage'
      pip install -r backend/requirements.txt
      echo $(pwd)
    init: |
      echo 'Beginning init stage'
      python backend/manage.py migrate
    command: |
      echo 'Beginning command stage'
      python backend/manage.py createsuperuser --no-input
      echo $(pwd)
      python backend/manage.py runserver