ports:
  - port: 8000
    visibility: public
    onOpen: open-preview

tasks:
  - before: |
      pip install -r backend/requirements.txt
      echo $(pwd)
    init: |
      python backend/manage.py migrate
      echo $DJANGO_SUPERUSER_USERNAME
      cat backend/create_superuser.py | python backend/manage.py shell
    command: |
      echo $(pwd)
      python backend/manage.py runserver