ports:
  - port: 8000
    visibility: public
  - port: 3000
    visibility: public

tasks:
  - before: |
      pip install -r backend/requirements.txt
    init: |
      python backend/manage.py migrate
      python backend/manage.py loaddata starter-data)
    command: |
      python backend/manage.py createsuperuser --no-input
      python backend/manage.py runserver
    name: Backend Server
    openMode: split-right
  - init: (cd frontend ; npm install)
    command: |
      python set_proxy.py
      (cd frontend ; npm start)
    openMode: split-right
    name: Frontend Server