ports:
  - port: 8000
    visibility: public
    onOpen: open-preview

tasks:
  - before: |
      pip install -r backend/requirements.txt
      echo $(pwd)
    init: |
      python backend/manage.py migrate
      echo $DJANGO_SUPERUSER_USERNAME
      python backend/manage.py createsuperuser --noinput \
        username=$DJANGO_SUPERUSER_USERNAME \
        password=$DJANGO_SUPERUSER_PASSWORD \
        email=$DJANGO_SUPERUSER_EMAIL
    command: |
      echo $(pwd)
      python backend/manage.py runserver