ports:
  - port: 8000
    visibility: public
    onOpen: open-preview
  - port: 3000
    visibility: public
    onOpen: open-preview

tasks:
  - before: |
      pip install -r backend/requirements.txt
    init: |
      npm install bootstrap@4.6.0 reactstrap@8.9.0 --legacy-peer-deps
      python backend/manage.py migrate
    command: |
      python backend/manage.py createsuperuser --no-input
      python backend/manage.py runserver
  - init: npm install bootstrap@4.6.0 reactstrap@8.9.0 --legacy-peer-deps
    command: |
      cd frontend
      npm start
    openMode: split-right