ports:
  - port: 8000
    visibility: public
  - port: 3000
    visibility: public
    onOpen: open-preview

tasks:
  - before: |
      pip install -r backend/requirements.txt
    init: |
      python backend/manage.py migrate
    command: |
      python backend/manage.py createsuperuser --no-input
      python backend/manage.py runserver
    name: Backend Server
    openMode: split-right
  - init: (cd frontend ; npm install axios@0.21.1 bootstrap@4.6.0 reactstrap@8.9.0 --legacy-peer-deps)
    command: |
      python set_proxy.py
      (cd frontend ; npm start)
    openMode: split-right
    name: Frontend Server