tasks:
  - before: |
      pip install -r backend/requirements.txt
      echo $(pwd)
    init: |
      python backend/manage.py migrate
    command: |
      echo $(pwd)
      python backend/manage.py runserver